name: my_website
description: A new Jaspr project
version: 0.0.1

environment:
  sdk: '>=3.8.0 <4.0.0'

dependencies:
  jaspr: ^0.21.6
  jaspr_router: ^0.7.3

dev_dependencies:
  build_runner: ^2.6.0
  build_web_compilers: ^4.3.2
  jaspr_builder: ^0.21.6
  jaspr_lints: ^0.5.1
  lints: ^5.0.0

jaspr:
  mode: static

